# Javascript Node CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-javascript/ for more details
#
version: 2
jobs:
  build:
    docker:

      - image: circleci/node:9.5.0

    working_directory: ~/nicolaic-website

    steps:
      - checkout
      - run:
        name: Install dependencies
        working_directory: /
        command: |
          apt-get -y -qq update
          apt-get -y -qq install python3.4-dev
          curl -O https://bootstrap.pypa.io/get-pip.py
          python3.4 get-pip.py --user
          pip install awscli --upgrade --user

      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "package.json" }}
          # fallback to using the latest cache if no exact match is found
          - v1-dependencies-

      - run: yarn install

      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}

      - run: npm run test

      - run:
          name: Deploy to S3 if tests pass and branch is Master
          command: aws s3 sync nicolaic-website s3://nicolaic.com --delete